/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.portal.vo;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2010-07-22 16:19:33
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class PtModuleVO extends SuperVO {
	private java.lang.String pk_module;
	private java.lang.String moduleid;
	private nc.vo.pub.lang.UFBoolean activeflag;
	private java.lang.String title;
	private java.lang.String pk_group;
	private java.lang.String parentid;
	private java.lang.String dependentid;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_MODULE = "pk_module";
	public static final String MODULEID = "moduleid";
	public static final String ACTIVEFLAG = "activeflag";
	public static final String TITLE = "title";
	public static final String PK_GROUP = "pk_group";
	public static final String PARENTID = "parentid";
	public static final String DEPENDENTID = "dependentid";
			
	/**
	 * 属性pk_module的Getter方法.
	 * 创建日期:2010-07-22 16:19:33
	 * @return java.lang.String
	 */
	public java.lang.String getPk_module () {
		return pk_module;
	}   
	/**
	 * 属性pk_module的Setter方法.
	 * 创建日期:2010-07-22 16:19:33
	 * @param newPk_module java.lang.String
	 */
	public void setPk_module (java.lang.String newPk_module ) {
	 	this.pk_module = newPk_module;
	} 	  
	/**
	 * 属性moduleid的Getter方法.
	 * 创建日期:2010-07-22 16:19:33
	 * @return java.lang.String
	 */
	public java.lang.String getModuleid () {
		return moduleid;
	}   
	/**
	 * 属性moduleid的Setter方法.
	 * 创建日期:2010-07-22 16:19:33
	 * @param newModuleid java.lang.String
	 */
	public void setModuleid (java.lang.String newModuleid ) {
	 	this.moduleid = newModuleid;
	} 	  
	/**
	 * 属性activeflag的Getter方法.
	 * 创建日期:2010-07-22 16:19:33
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getActiveflag () {
		return activeflag;
	}   
	/**
	 * 属性activeflag的Setter方法.
	 * 创建日期:2010-07-22 16:19:33
	 * @param newActiveflag nc.vo.pub.lang.UFBoolean
	 */
	public void setActiveflag (nc.vo.pub.lang.UFBoolean newActiveflag ) {
	 	this.activeflag = newActiveflag;
	} 	  
	/**
	 * 属性title的Getter方法.
	 * 创建日期:2010-07-22 16:19:33
	 * @return java.lang.String
	 */
	public java.lang.String getTitle () {
		return title;
	}   
	/**
	 * 属性title的Setter方法.
	 * 创建日期:2010-07-22 16:19:33
	 * @param newTitle java.lang.String
	 */
	public void setTitle (java.lang.String newTitle ) {
	 	this.title = newTitle;
	} 	  
	/**
	 * 属性pk_group的Getter方法.
	 * 创建日期:2010-07-22 16:19:33
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.
	 * 创建日期:2010-07-22 16:19:33
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性parentid的Getter方法.
	 * 创建日期:2010-07-22 16:19:33
	 * @return java.lang.String
	 */
	public java.lang.String getParentid () {
		return parentid;
	}   
	/**
	 * 属性parentid的Setter方法.
	 * 创建日期:2010-07-22 16:19:33
	 * @param newParentid java.lang.String
	 */
	public void setParentid (java.lang.String newParentid ) {
	 	this.parentid = newParentid;
	} 	  
	/**
	 * 属性dependentid的Getter方法.
	 * 创建日期:2010-07-22 16:19:33
	 * @return java.lang.String
	 */
	public java.lang.String getDependentid () {
		return dependentid;
	}   
	/**
	 * 属性dependentid的Setter方法.
	 * 创建日期:2010-07-22 16:19:33
	 * @param newDependentid java.lang.String
	 */
	public void setDependentid (java.lang.String newDependentid ) {
	 	this.dependentid = newDependentid;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2010-07-22 16:19:33
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2010-07-22 16:19:33
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2010-07-22 16:19:33
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2010-07-22 16:19:33
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2010-07-22 16:19:33
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2010-07-22 16:19:33
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_module";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2010-07-22 16:19:33
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "pt_module";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2010-07-22 16:19:33
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "pt_module";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2010-07-22 16:19:33
	  */
     public PtModuleVO() {
		super();	
	}    
} 


