/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.uap.portal.vo;
	
import nc.vo.pub.*;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2010-07-22 16:55:56
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class PtThemeVO extends SuperVO {
	private java.lang.String pk_theme;
	private java.lang.String themeid;
	private nc.vo.pub.lang.UFBoolean activeflag;
	private java.lang.String title;
	private java.lang.String pk_group;
	private java.lang.String parentid;
	private java.lang.String lfwthemeid;
	private java.lang.String i18nname;
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String PK_THEME = "pk_theme";
	public static final String THEMEID = "themeid";
	public static final String ACTIVEFLAG = "activeflag";
	public static final String TITLE = "title";
	public static final String PK_GROUP = "pk_group";
	public static final String PARENTID = "parentid";
	public static final String LFWTHEMEID = "lfwthemeid";
	public static final String I18NNAME = "i18nname";
			
	/**
	 * 属性pk_theme的Getter方法.
	 * 创建日期:2010-07-22 16:55:56
	 * @return java.lang.String
	 */
	public java.lang.String getPk_theme () {
		return pk_theme;
	}   
	/**
	 * 属性pk_theme的Setter方法.
	 * 创建日期:2010-07-22 16:55:56
	 * @param newPk_theme java.lang.String
	 */
	public void setPk_theme (java.lang.String newPk_theme ) {
	 	this.pk_theme = newPk_theme;
	} 	  
	/**
	 * 属性themeid的Getter方法.
	 * 创建日期:2010-07-22 16:55:56
	 * @return java.lang.String
	 */
	public java.lang.String getThemeid () {
		return themeid;
	}   
	/**
	 * 属性themeid的Setter方法.
	 * 创建日期:2010-07-22 16:55:56
	 * @param newThemeid java.lang.String
	 */
	public void setThemeid (java.lang.String newThemeid ) {
	 	this.themeid = newThemeid;
	} 	  
	/**
	 * 属性activeflag的Getter方法.
	 * 创建日期:2010-07-22 16:55:56
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getActiveflag () {
		return activeflag;
	}   
	/**
	 * 属性activeflag的Setter方法.
	 * 创建日期:2010-07-22 16:55:56
	 * @param newActiveflag nc.vo.pub.lang.UFBoolean
	 */
	public void setActiveflag (nc.vo.pub.lang.UFBoolean newActiveflag ) {
	 	this.activeflag = newActiveflag;
	} 	  
	/**
	 * 属性title的Getter方法.
	 * 创建日期:2010-07-22 16:55:56
	 * @return java.lang.String
	 */
	public java.lang.String getTitle () {
		return title;
	}   
	/**
	 * 属性title的Setter方法.
	 * 创建日期:2010-07-22 16:55:56
	 * @param newTitle java.lang.String
	 */
	public void setTitle (java.lang.String newTitle ) {
	 	this.title = newTitle;
	} 	  
	/**
	 * 属性pk_group的Getter方法.
	 * 创建日期:2010-07-22 16:55:56
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.
	 * 创建日期:2010-07-22 16:55:56
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性parentid的Getter方法.
	 * 创建日期:2010-07-22 16:55:56
	 * @return java.lang.String
	 */
	public java.lang.String getParentid () {
		return parentid;
	}   
	/**
	 * 属性parentid的Setter方法.
	 * 创建日期:2010-07-22 16:55:56
	 * @param newParentid java.lang.String
	 */
	public void setParentid (java.lang.String newParentid ) {
	 	this.parentid = newParentid;
	} 	  
	/**
	 * 属性lfwthemeid的Getter方法.
	 * 创建日期:2010-07-22 16:55:56
	 * @return java.lang.String
	 */
	public java.lang.String getLfwthemeid () {
		return lfwthemeid;
	}   
	/**
	 * 属性lfwthemeid的Setter方法.
	 * 创建日期:2010-07-22 16:55:56
	 * @param newLfwthemeid java.lang.String
	 */
	public void setLfwthemeid (java.lang.String newLfwthemeid ) {
	 	this.lfwthemeid = newLfwthemeid;
	} 	  
	/**
	 * 属性i18nname的Getter方法.
	 * 创建日期:2010-07-22 16:55:56
	 * @return java.lang.String
	 */
	public java.lang.String getI18nname () {
		return i18nname;
	}   
	/**
	 * 属性i18nname的Setter方法.
	 * 创建日期:2010-07-22 16:55:56
	 * @param newI18nname java.lang.String
	 */
	public void setI18nname (java.lang.String newI18nname ) {
	 	this.i18nname = newI18nname;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2010-07-22 16:55:56
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2010-07-22 16:55:56
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2010-07-22 16:55:56
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2010-07-22 16:55:56
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2010-07-22 16:55:56
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2010-07-22 16:55:56
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_theme";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2010-07-22 16:55:56
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "pt_theme";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2010-07-22 16:55:56
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "pt_theme";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2010-07-22 16:55:56
	  */
     public PtThemeVO() {
		super();	
	}    
} 


